apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: appmesh
  region: us-east-1
nodeGroups:
  - name: default
    instanceType: m5.large
    desiredCapacity: 2
    volumeSize: 120
    iam:
      withAddonPolicies:
        appMesh: true
        xRay: true